### ISSUE TITLE
How can I pass a commit callback

### ISSUE THREAD

**Issue by vuza** [nodefluent/node-sinek#37]
Hi!
Is there a specific reason, why you overwrite the commit callback? How can I receive commit errors? Wouldn't it be nice to pass an optional callback to the commit methods, which overwrites the default callback? Or am I overlooking something?
https://github.com/nodefluent/node-sinek/blob/452b16b76a5363ccfb1f20178fe474789337e21c/lib/librdkafka/NConsumer.js#L191
Thank you!

**Comment by krystianity** [comment]
Hi @vuza, yup the reason is that I planned to use it to offer a "real" commit callback on message or commit basis in a future version of the API (did not really need it so far) - but you are right, I shouldn't overwrite it, without giving you an option to register your own callback.

I have fixed that in sinek@6.13.0
(NOTE: I have also upgraded node-rdkafka to 2.2.0)
